### ISSUE TITLE
When will the code be open sourced

### ISSUE THREAD

**Issue by 24werewolf** [ZrrSkywalker/MonoDETR#2]
Hi， When will the code be open sourced

**Comment by ZrrSkywalker** [comment]
Thanks for your interest. The code is being wrapped and will be released soon.

**Comment by hey-it-s-me** [comment]
> Thanks for your interest. The code is being wrapped and will be released soon.

May I know how long will the code be released, I hope to quote it in my graduation thesis

**Comment by ZrrSkywalker** [comment]
@hey-it-s-me Will be released in two days.

**Comment by ZrrSkywalker** [comment]
@hey-it-s-me @24werewolf Thanks for your interest! The code has been released.

**Comment by ZrrSkywalker** [comment]
@Yibin122 Yes, we will update the ckpts soon.
