### ISSUE TITLE
Common question about backbone

### ISSUE THREAD

**Issue by hey-it-s-me** [ZrrSkywalker/MonoDETR#6]
@ZrrSkywalker Excellent work! 
But I am confused about whether the backbone  used in models namely Resnet 50 is a pre-trained model.

**Comment by hey-it-s-me** [comment]
When loading backbone, the setting 'pretrained=is_main_process()' is what I am confused

**Comment by ZrrSkywalker** [comment]
Thanks for your interest. We use  the weights pre-trained by ImageNet for ResNEt-50 and will load them before training.
