### ISSUE TITLE
Question on pretrained model.

### ISSUE THREAD

**Issue by rust-in** [ZrrSkywalker/MonoDETR#9]
Thank you for your solid work!

I'm having some problems reproducing the results. By running the default training script, the results I tested are on average 3% lower than the official results.
So I'm wondering if you could provide the pre-trained model? Or are there any changes to the hyperparameters?

Looking forward to your reply.

**Comment by ZrrSkywalker** [comment]
Thanks for your interest!
The results jitter +-1 moderate AP by our experiments for different pytorch versions and GPU. Ours are "pytorch 1.7.1+cu110" and "a single GeForce RTX 3090". 
The pre-trained ResNet50 will be automatically downloaded during the first-time training. The trained checkpoints of MonoDETR will be released soon.

Thanks!
